version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: richisntreal
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      RICHISNTREAL_MYSQL_HOST: db
      RICHISNTREAL_MYSQL_PORT: "3306"
      RICHISNTREAL_MYSQL_USERNAME: root
      RICHISNTREAL_MYSQL_PASSWORD: password
      RICHISNTREAL_MYSQL_DATABASE: richisntreal
      RICHISNTREAL_APP_PORT: "8080"
      RICHISNTREAL_APP_JWTSECRET: supersecret

volumes:
  db-data:
